# Generated by Django 5.0.8 on 2024-10-19 09:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"verbose_name_plural": "Posts"},
        ),
        migrations.RenameField(
            model_name="post",
            old_name="created_at",
            new_name="created",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="updated_at",
            new_name="updated",
        ),
        migrations.AddField(
            model_name="post",
            name="publish",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
