# Generated by Django 5.0.8 on 2024-10-19 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_options_rename_created_at_post_created_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="created",
        ),
        migrations.RemoveField(
            model_name="post",
            name="publish",
        ),
        migrations.RemoveField(
            model_name="post",
            name="updated",
        ),
    ]
